version: 2

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - gocritic
    - errcheck

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-use-default: false